
import "./globals.css";
import {Providers} from './provider'
import Navbar from "./components/navbar/navbar";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
         <script
          defer
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAP_API}&libraries=places`}
        ></script>
      </head>
       <body   >
        <Providers>
        <Navbar />
        {children}

        </Providers>
      


      </body>
    </html>
  );
}
